# Generated by Django 6.0.4 on 2026-04-24 20:30

import django.core.validators
import django.db.models.deletion
import lostandfound.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lostandfound.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='lostandfound.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('useranme', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[lostandfound.models.validateemail])),
                ('password', models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='claim',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostandfound.founditem'),
        ),
        migrations.AddField(
            model_name='notification',
            name='claimreq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostandfound.claim'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='lostandfound.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='lostandfound.user'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_posts', to='lostandfound.user'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_posts', to='lostandfound.user'),
        ),
        migrations.AddField(
            model_name='claim',
            name='requestby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimrequests', to='lostandfound.user'),
        ),
    ]
