# Generated by Django 6.0.4 on 2026-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0007_alter_claim_image_alter_founditem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
