# Generated by Django 6.0.4 on 2026-05-12 22:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0008_alter_claim_image_alter_founditem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('scheduled_time', models.DateTimeField()),
                ('exchange_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='lostandfound.claim')),
            ],
        ),
    ]
